### ISSUE TITLE
Error with parsing.

### ISSUE THREAD

**Issue by iRealistiX** [kyurime/gdrpc#10]
**What happens?**
Error when editing the config file.

**How did it happen?**
Describe the steps taken in order to recreate the bug.
1. Edit the config file
```toml
# When you edit a level.
[editor]
detail = "Editing {name}."
state = ""
smalltext = "{objects} Object(s)."
reset_timestamp = false
```
2. Save, Open Geometry dash.
3. Try editing a level

**What was supposed to happen?**
A error box pops up with "Error parsing `{objects} Object(s)`"

Log file : [gdrpc.log](https://github.com/kyurime/gdrpc/files/5927945/gdrpc.log)
